# Generated by Django 4.2.7 on 2024-05-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_club_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('idNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_residence', models.CharField(blank=200, max_length=200, null=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees_profile')),
                ('id_front_picture', models.ImageField(blank=True, null=True, upload_to='employees_id')),
                ('id_back_picture', models.ImageField(blank=True, null=True, upload_to='employees_id')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employed_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
    ]
