# Generated by Django 4.2.7 on 2024-06-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('clubs', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksedited',
            name='who_stocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='who_stocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='advances',
            name='advances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advancestype'),
        ),
    ]
