# Generated by Django 4.2.7 on 2023-11-20 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_date_alter_stock_item_alter_transaction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 20, 8, 37, 42, 402487, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
