# Generated by Django 4.2.7 on 2024-06-07 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 7, 15, 37, 27, 179784, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
