# Generated by Django 4.2.7 on 2023-11-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity_sold',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
