# Generated by Django 4.2.7 on 2023-11-20 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_quantity_sold_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 20, 9, 28, 0, 209293, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
