# Generated by Django 4.2.7 on 2024-06-08 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_salesrecord_recieved_stock_alter_expenses_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='employee',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='who_recorded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='recieved_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
