# Generated by Django 4.2.7 on 2023-11-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stock_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='item',
            new_name='product',
        ),
    ]
