# Generated by Django 4.2.7 on 2024-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_salesrecord_employee_salesrecord_who_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='opening_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
