# Generated by Django 4.2.7 on 2023-11-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.club'),
            preserve_default=False,
        ),
    ]
