# Generated by Django 4.2.7 on 2024-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_salesrecord_closing_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
