# Generated by Django 4.2.7 on 2023-11-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_club_stock_club_transaction_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='club',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='club',
        ),
    ]
