# Generated by Django 4.2.7 on 2024-06-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_salesrecord_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='who_stocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
