# Generated by Django 4.2.7 on 2024-06-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stocks_who_stocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='total_price',
        ),
    ]
