# Generated by Django 4.2.7 on 2024-05-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('employees', '0002_alter_employeesaccount_employed_in'),
        ('api', '0011_club_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField()),
                ('receipt_picture', models.ImageField(blank=True, null=True, upload_to='expenes_reciept')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('date_stocked', models.DateField(blank=True, null=True)),
                ('receipt_picture', models.ImageField(blank=True, null=True, upload_to='receipts')),
                ('edited', models.BooleanField(default=False)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('who_stocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount')),
            ],
        ),
        migrations.CreateModel(
            name='StocksEdited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.BooleanField(default=True)),
                ('date_time_edited', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='club',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='club',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='club',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks'),
        ),
    ]
