# Generated by Django 4.2.7 on 2024-06-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_stocks_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='quantity',
            new_name='sales_quantity',
        ),
    ]
