# Generated by Django 4.2.7 on 2024-05-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employed_in_employeesaccount_club_and_more'),
        ('clubs', '0002_owner_club_owner'),
        ('api', '0012_expenses_products_salesrecord_stocks_stocksedited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksedited',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employeesaccount'),
            preserve_default=False,
        ),
    ]
