# Generated by Django 4.2.7 on 2024-05-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expenses_employee_salesrecord_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksedited',
            old_name='employee',
            new_name='who_stocked',
        ),
    ]
