# Generated by Django 4.2.7 on 2024-05-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_employee_stocksedited_who_stocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='edited',
        ),
    ]
