# Generated by Django 4.2.7 on 2024-05-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_owner_first_name_owner_last_name'),
        ('api', '0015_remove_stocks_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='pub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
            preserve_default=False,
        ),
    ]
