# Generated by Django 4.2.7 on 2024-05-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_expenses_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advances_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField()),
                ('advances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advancestype')),
            ],
        ),
    ]
